### ISSUE TITLE
Try to resend when scanner-proxy gets a http connect error

### ISSUE THREAD

**Issue by jgrund** [whamcloud/device-scanner#136]
There may be cases where the manager is unreachable (network hiccup, it was stopped, etc...)

In those cases, we will get an error like:

```
Apr 04 22:33:38 mds2.lfs.local node[10024]: Proxy connecting to device scanner...
Apr 04 23:37:45 mds2.lfs.local node[10024]: Unable to generate HTTPS request connect ECONNREFUSED 10.73.10.10:443, Error: connect ECONNREFUSED 10.73.10.10:443
Apr 04 23:37:45 mds2.lfs.local node[10024]: at Object.exports._errnoException (util.js:1020:11)
Apr 04 23:37:45 mds2.lfs.local node[10024]: at exports._exceptionWithHostPort (util.js:1043:20)
Apr 04 23:37:45 mds2.lfs.local node[10024]: at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
```

In the scanner-proxy.

That error comes from: 

https://github.com/intel-hpdd/device-scanner/blob/83e45faffdf678b34b01fa6f0ed0f6575cba4a00/IML.ScannerProxyDaemon/src/Transmit.fs#L26-L28

We should probably retry the send (perhaps once a minute) until we get a success. While doing this, we should account for new incoming data and only keep the last item for sending.

**Comment by jgrund** [comment]
scanner-proxy has been removed from this repo
