### ISSUE TITLE
UNIX socket fails from time to time

### ISSUE THREAD

**Issue by AlexTalker** [whamcloud/device-scanner#252]
When scanning for file systems, from time to time in `device-scanner.service` log I see following:
```
Apr 25 23:42:37 oss1 systemd[1]: Started IML Device Scanner Daemon.
Apr 25 23:42:37 oss1 systemd[1]: Starting IML Device Scanner Daemon...
Apr 25 23:45:36 oss1 node[1528]: Unexpected socket error: write EPIPE
Apr 25 23:45:36 oss1 node[1528]: trace: Error: write EPIPE
Apr 25 23:45:36 oss1 node[1528]: at _errnoException (util.js:1022:11)
Apr 25 23:45:36 oss1 node[1528]: at WriteWrap.afterWrite [as oncomplete] (net.js:867:14)
Apr 25 23:49:55 oss1 node[1528]: Unexpected socket error: write EPIPE
Apr 25 23:49:55 oss1 node[1528]: trace: Error: write EPIPE
Apr 25 23:49:55 oss1 node[1528]: at _errnoException (util.js:1022:11)
Apr 25 23:49:55 oss1 node[1528]: at WriteWrap.afterWrite [as oncomplete] (net.js:867:14)
```

I can't figure out what causes this. Besides, upstream version seems to use different language but does not submitted with production packages. I used `iml-device-scanner-2.2.0-198.el7.x86_64`.
Can you give me a hit on what's wrong?

Scanning seems to stuck after this event and always fails by timeout.

**Comment by jgrund** [comment]
@AlexTalker `EPIPE` most likely means the other side has hung up. Can you correlate this with any errors elsewhere in IML / IML agent?

**Comment by AlexTalker** [comment]
I noticed that `detect_scan` seems to hang on after handling a few devices during the same stage. Sometimes this followed by socket `timed out`, sometimes not, so no luck in this direction but your wire protocol seems to be weak - too many parsing errors thrown out. About `68` multi-path drives connected to the target host and `6` `OST` created on it. Is that too much?
Also, I wonder, what `swap-emitter.timer` do?
Does it trigger anything?

**Comment by jgrund** [comment]
> too many parsing errors thrown out. 

Can you share any of those? if you see parse errors it's bug that needs fixing.

> About 68 multi-path drives connected to the target host and 6 OST created on it. Is that too much?

Nope, should be able to handle much more than that.

> Also, I wonder, what swap-emitter.timer do?

It triggers `swap-emitter.service` which scans for swap devices.

**Comment by AlexTalker** [comment]
@jgrund It's a really huge output data but general exception looks like:
```
Extra data: line 2 column 1 - line 26058 column 1 (char 252426 - 6577464282)
```

**Comment by AlexTalker** [comment]
In any case, from command-line, `"Stream"` command executes fine most of the time.

**Comment by AlexTalker** [comment]
Now I wonder, if this is a consequence of first paring error.
As it is clear to me now, you set timeout of `10s` per OPERATION and the operation is reading `1k` of data from socket of the service. But, if data is inconsistent, then this cycle is infinite.

**Comment by AlexTalker** [comment]
I refer to this cycle:
https://github.com/whamcloud/iml-agent/blob/master/chroma_agent/device_plugins/block_devices.py#L42

**Comment by AlexTalker** [comment]
@jgrund I'm not much experienced in `F#`, so, tell me, after writing down response to command, a connection is closed?
If not, a valid response contains `\n` anywhere beside the end?

**Comment by jgrund** [comment]
@AlexTalker device-scanner streams newline delimited JSON (both for input and output), I.E. each message sent down the stream is terminated by a newline. That happens here on the output side:

https://github.com/whamcloud/device-scanner/blob/8c725e9bcac4709ef5782dd0637c665f742beafb/IML.DeviceScannerDaemon/src/Connections.fs#L44-L47

The client is responsible for closing the connection when they are finished.

**Comment by AlexTalker** [comment]
@jgrund So, correct me if I'm wrong. By some coincidence, `scanner_cmd` receives an invalid `JSON`. As far as I know, if you do not `humanize` it, then `\n` in response is the one and only.
Thus, unless it is expected to receive multiple messages in response to a single command, is there a point for the infinite cycle in case of syntax error?

**Comment by AlexTalker** [comment]
Also, I checked, you can't parse multiple JSON objects, thus, there's no point for waiting after a failure as it seems to me. Or, the buffer shall be cleared.

**Comment by jgrund** [comment]
I'm not sure where you are seeing an infinite cycle, are you not seeing a socket timeout after 10s?

**Comment by AlexTalker** [comment]
```
[25/Apr/2019:19:09:30] daemon INFO Searching device /dev/disk/by-id/scsi-SQEMU_l_ost0_0A9B7697-702E-43A2-B67A-47EE32F1C995 of type linux, uuid 20cb2072-6cae-47be-b384
-e4cfb0751ea0 for a Lustre filesystem
[25/Apr/2019:19:09:34] daemon WARNING Scan Error[1]: Extra data: line 2 column 1 - line 46 column 1 (char 252426 - 11359170)
[25/Apr/2019:19:09:37] daemon WARNING Scan Error[2]: Extra data: line 2 column 1 - line 47 column 1 (char 252426 - 11611596)
[25/Apr/2019:19:09:39] daemon WARNING Scan Error[3]: Extra data: line 2 column 1 - line 106 column 1 (char 252426 - 26504730)
[25/Apr/2019:19:09:42] daemon WARNING Scan Error[4]: Extra data: line 2 column 1 - line 107 column 1 (char 252426 - 26757156)
[25/Apr/2019:19:09:44] daemon WARNING Scan Error[5]: Extra data: line 2 column 1 - line 166 column 1 (char 252426 - 41650290)
[25/Apr/2019:19:09:50] daemon WARNING Scan Error[6]: Extra data: line 2 column 1 - line 226 column 1 (char 252426 - 56795850)
[25/Apr/2019:19:09:52] daemon WARNING Scan Error[7]: Extra data: line 2 column 1 - line 227 column 1 (char 252426 - 57048276)
[25/Apr/2019:19:09:55] daemon WARNING Scan Error[8]: Extra data: line 2 column 1 - line 286 column 1 (char 252426 - 71941410)
[25/Apr/2019:19:09:59] daemon WARNING Scan Error[9]: Extra data: line 2 column 1 - line 346 column 1 (char 252426 - 87086970)
[25/Apr/2019:19:10:04] daemon WARNING Scan Error[10]: Extra data: line 2 column 1 - line 406 column 1 (char 252426 - 102232530)
[25/Apr/2019:19:10:09] daemon WARNING Scan Error[11]: Extra data: line 2 column 1 - line 439 column 1 (char 252426 - 110562588)
[25/Apr/2019:19:10:09] daemon WARNING Scan Error[12]: Extra data: line 2 column 1 - line 466 column 1 (char 252426 - 117378090)
[25/Apr/2019:19:10:14] daemon WARNING Scan Error[13]: Extra data: line 2 column 1 - line 526 column 1 (char 252426 - 132523650)
[25/Apr/2019:19:10:19] daemon WARNING Scan Error[14]: Extra data: line 2 column 1 - line 586 column 1 (char 252426 - 147669210)
[25/Apr/2019:19:10:24] daemon WARNING Scan Error[15]: Extra data: line 2 column 1 - line 646 column 1 (char 252426 - 162814770)
[25/Apr/2019:19:10:29] daemon WARNING Scan Error[16]: Extra data: line 2 column 1 - line 706 column 1 (char 252426 - 177960330)
[25/Apr/2019:19:10:34] daemon WARNING Scan Error[17]: Extra data: line 2 column 1 - line 766 column 1 (char 252426 - 193105890)
[25/Apr/2019:19:10:39] daemon WARNING Scan Error[18]: Extra data: line 2 column 1 - line 826 column 1 (char 252426 - 208251450)
[25/Apr/2019:19:10:44] daemon WARNING Scan Error[19]: Extra data: line 2 column 1 - line 886 column 1 (char 252426 - 223397010)
[25/Apr/2019:19:10:49] daemon WARNING Scan Error[20]: Extra data: line 2 column 1 - line 915 column 1 (char 252426 - 230717364)
[25/Apr/2019:19:10:50] daemon WARNING Scan Error[21]: Extra data: line 2 column 1 - line 946 column 1 (char 252426 - 238542570)
[25/Apr/2019:19:10:54] daemon WARNING Scan Error[22]: Extra data: line 2 column 1 - line 986 column 1 (char 252426 - 248639610)
```

Seems to me, this was not supposed to be this way.

**Comment by AlexTalker** [comment]
@jgrund Yes, I see the timeout but as I pointed out, it is a timeout per OPERATION.
https://docs.python.org/3/library/socket.html#socket.socket.settimeout
And operation  in our case is receiving `1K` of data:
https://docs.python.org/3/library/socket.html#socket.socket.recv
As you can see, we receive a bit more in no time at all :trollface:

**Comment by AlexTalker** [comment]
Stacktrace:
```
>>> detect_scan()
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/chroma_agent/action_plugins/detect_scan.py", line 159, in detect_scan
    local_targets = LocalTargets(settings["target_devices"])
  File "/usr/lib/python2.7/site-packages/chroma_agent/action_plugins/detect_scan.py", line 55, in __init__
    ndp = get_normalized_device_table()
  File "/usr/lib/python2.7/site-packages/chroma_agent/device_plugins/block_devices.py", line 308, in get_normalized_device_table
    device-scanner to produce a ndt
  File "/usr/lib/python2.7/site-packages/chroma_agent/device_plugins/block_devices.py", line 45, in scanner_cmd
    out += client.recv(1024)
KeyboardInterrupt
```

**Comment by jgrund** [comment]
Closing as https://github.com/whamcloud/iml-agent/pull/91 has landed.
